import { StudentGradableEventResponseDTO } from "@/interfaces/api/DTO";

export const RoadmapService = {
  getRoadmapData: async (): Promise<StudentGradableEventResponseDTO[]> => {
    return [
      {
        id: 1,
        type: "test",
        name: "Kartkówka 1",
        topic: "Instrukcje sterujące",
        gainedXp: "1.5",
        orderIndex: 1,
        hasReward: false,
        isLocked: false,
      },
      {
        id: 15,
        type: "assignment",
        name: "Laboratorium 1",
        topic: "Instrukcje sterujące w Javie",
        gainedXp: "2.0",
        orderIndex: 2,
        hasReward: false,
        isLocked: false,
      },
      {
        id: 2,
        type: "test",
        name: "Kartkówka 2",
        topic: "Model obiektowy",
        orderIndex: 3,
        hasReward: false,
        isLocked: false,
      },
      {
        id: 16,
        type: "assignment",
        name: "Laboratorium 2",
        topic: "Model obiektowy",
        orderIndex: 4,
        hasReward: true,
        isLocked: false,
      },
      {
        id: 30,
        type: "assignment",
        name: "Dziady",
        topic: "Straszenie programistów",
        orderIndex: 5,
        hasReward: true,
        isLocked: true,
      },
      {
        id: 33,
        type: "assignment",
        name: "Dziady 2",
        topic: "Straszenie programistów 2",
        orderIndex: 5,
        hasReward: true,
        isLocked: false,
      },
      {
        id: 3,
        type: "test",
        name: "Kartkówka 3",
        topic: "Interakcje między obiektami",
        orderIndex: 6,
        hasReward: false,
        isLocked: false,
      },
      {
        id: 17,
        type: "assignment",
        name: "Laboratorium 3",
        topic: "Interakcje między obiektami",
        orderIndex: 7,
        hasReward: false,
        isLocked: false,
      },
      {
        id: 4,
        type: "test",
        name: "Kartkówka 4",
        topic: "Interfejsy i mapy",
        orderIndex: 8,
        hasReward: false,
        isLocked: false,
      },
      {
        id: 18,
        type: "assignment",
        name: "Laboratorium 4",
        topic: "Interfejsy i mapy",
        orderIndex: 9,
        hasReward: false,
        isLocked: false,
      },
      {
        id: 5,
        type: "test",
        name: "Kartkówka 5",
        topic: "Dziedziczenie",
        orderIndex: 10,
        hasReward: false,
        isLocked: false,
      },
      {
        id: 19,
        type: "assignment",
        name: "Laboratorium 5",
        topic: "Dziedziczenie",
        orderIndex: 11,
        hasReward: true,
        isLocked: false,
      },
      {
        id: 6,
        type: "test",
        name: "Kartkówka 6",
        topic: "Refactoring kodu",
        orderIndex: 12,
        hasReward: false,
        isLocked: false,
      },
      {
        id: 20,
        type: "assignment",
        name: "Laboratorium 6",
        topic: "Refactoring kodu",
        orderIndex: 13,
        hasReward: false,
        isLocked: false,
      },
      {
        id: 7,
        type: "test",
        name: "Kartkówka 7",
        topic: "Wielowątkowość",
        orderIndex: 14,
        hasReward: false,
        isLocked: false,
      },
      {
        id: 21,
        type: "assignment",
        name: "Laboratorium 7",
        topic: "Wielowątkowość",
        orderIndex: 15,
        hasReward: false,
        isLocked: false,
      },
      {
        id: 8,
        type: "test",
        name: "Kartkówka 8",
        topic: "Interfejs graficzny",
        orderIndex: 16,
        hasReward: true,
        isLocked: false,
      },
      {
        id: 22,
        type: "assignment",
        name: "Laboratorium 8",
        topic: "Interfejs graficzny",
        orderIndex: 17,
        hasReward: false,
        isLocked: false,
      },
      {
        id: 9,
        type: "test",
        name: "Kartkówka 9",
        topic: "Lambdy, streamy i zarządzanie zasobami",
        orderIndex: 18,
        hasReward: false,
        isLocked: false,
      },
      {
        id: 10,
        type: "test",
        name: "Kartkówka 10",
        topic: "Kotlin jako alternatywa dla Javy",
        orderIndex: 19,
        hasReward: false,
        isLocked: false,
      },
      {
        id: 11,
        type: "test",
        name: "Kartkówka 11",
        topic: "A może Rust?",
        orderIndex: 20,
        hasReward: false,
        isLocked: false,
      },
      {
        id: 12,
        type: "test",
        name: "Kartkówka 12",
        topic: "Jak wycentrować diva",
        orderIndex: 21,
        hasReward: false,
        isLocked: false,
      },
    ];
  },
};
