import { GradableEventResponseDTO } from "@/app/(logged-in)/course/EventSectionService";

export const RoadmapService = {
  getRoadmapData: async (): Promise<GradableEventResponseDTO[]> => {
    return [
      {
        id: 1,
        name: "Kartkówka 1",
        topic: "Instrukcje sterujące",
        gainedXp: 1.5,
        order: 1,
        hasChest: false,
        isLocked: false,
      },
      {
        id: 15,
        name: "Laboratorium 1",
        topic: "Instrukcje sterujące w Javie",
        gainedXp: 2.0,
        order: 2,
        hasChest: false,
        isLocked: false,
      },
      {
        id: 2,
        name: "Kartkówka 2",
        topic: "Model obiektowy",
        gainedXp: 0.0,
        order: 3,
        hasChest: false,
        isLocked: false,
      },
      {
        id: 16,
        name: "Laboratorium 2",
        topic: "Model obiektowy",
        gainedXp: 0.0,
        order: 4,
        hasChest: true,
        isLocked: false,
      },
      {
        id: 30,
        name: "Dziady",
        topic: "Straszenie programistów",
        gainedXp: 0.0,
        order: 5,
        hasChest: true,
        isLocked: true,
      },
      {
        id: 33,
        name: "Dziady 2",
        topic: "Straszenie programistów 2",
        gainedXp: 0.0,
        order: 5,
        hasChest: true,
        isLocked: false,
      },
      {
        id: 3,
        name: "Kartkówka 3",
        topic: "Interakcje między obiektami",
        gainedXp: 0.0,
        order: 6,
        hasChest: false,
        isLocked: false,
      },
      {
        id: 17,
        name: "Laboratorium 3",
        topic: "Interakcje między obiektami",
        gainedXp: 0.0,
        order: 7,
        hasChest: false,
        isLocked: false,
      },
      {
        id: 4,
        name: "Kartkówka 4",
        topic: "Interfejsy i mapy",
        gainedXp: 0.0,
        order: 8,
        hasChest: false,
        isLocked: false,
      },
      {
        id: 18,
        name: "Laboratorium 4",
        topic: "Interfejsy i mapy",
        gainedXp: 0.0,
        order: 9,
        hasChest: false,
        isLocked: false,
      },
      {
        id: 5,
        name: "Kartkówka 5",
        topic: "Dziedziczenie",
        gainedXp: 0.0,
        order: 10,
        hasChest: false,
        isLocked: false,
      },
      {
        id: 19,
        name: "Laboratorium 5",
        topic: "Dziedziczenie",
        gainedXp: 0.0,
        order: 11,
        hasChest: true,
        isLocked: false,
      },
      {
        id: 6,
        name: "Kartkówka 6",
        topic: "Refactoring kodu",
        gainedXp: 0.0,
        order: 12,
        hasChest: false,
        isLocked: false,
      },
      {
        id: 20,
        name: "Laboratorium 6",
        topic: "Refactoring kodu",
        gainedXp: 0.0,
        order: 13,
        hasChest: false,
        isLocked: false,
      },
      {
        id: 7,
        name: "Kartkówka 7",
        topic: "Wielowątkowość",
        gainedXp: 0.0,
        order: 14,
        hasChest: false,
        isLocked: false,
      },
      {
        id: 21,
        name: "Laboratorium 7",
        topic: "Wielowątkowość",
        gainedXp: 0.0,
        order: 15,
        hasChest: false,
        isLocked: false,
      },
      {
        id: 8,
        name: "Kartkówka 8",
        topic: "Interfejs graficzny",
        gainedXp: 0.0,
        order: 16,
        hasChest: true,
        isLocked: false,
      },
      {
        id: 22,
        name: "Laboratorium 8",
        topic: "Interfejs graficzny",
        gainedXp: 0.0,
        order: 17,
        hasChest: false,
        isLocked: false,
      },
      {
        id: 9,
        name: "Kartkówka 9",
        topic: "Lambdy, streamy i zarządzanie zasobami",
        gainedXp: 0.0,
        order: 18,
        hasChest: false,
        isLocked: false,
      },
      {
        id: 10,
        name: "Kartkówka 10",
        topic: "Kotlin jako alternatywa dla Javy",
        gainedXp: 0.0,
        order: 19,
        hasChest: false,
        isLocked: false,
      },
      {
        id: 11,
        name: "Kartkówka 11",
        topic: "A może Rust?",
        gainedXp: 0.0,
        order: 20,
        hasChest: false,
        isLocked: false,
      },
      {
        id: 12,
        name: "Kartkówka 12",
        topic: "Jak wycentrować diva",
        gainedXp: 0.0,
        order: 21,
        hasChest: false,
        isLocked: false,
      },
    ];
  },
};
