ALTER TABLE invitation_tokens RENAME TO tokens;
ALTER TABLE tokens DROP COLUMN IF EXISTS used;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS token_type VARCHAR(20);
ALTER TABLE tokens ALTER COLUMN token_type SET NOT NULL;
