CREATE TABLE project_groups
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    instructor_id BIGINT                                  NOT NULL,
    project_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_project_groups PRIMARY KEY (id)
);

CREATE TABLE project_groups_animals
(
    animal_id        BIGINT NOT NULL,
    project_group_id BIGINT NOT NULL
);

CREATE TABLE project_groups_project_variants
(
    project_group_id   BIGINT NOT NULL,
    project_variant_id BIGINT NOT NULL
);

CREATE TABLE project_variant_categories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id BIGINT                                  NOT NULL,
    name       VARCHAR(255),
    CONSTRAINT pk_project_variant_categories PRIMARY KEY (id)
);

CREATE TABLE project_variants
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_variant_category_id BIGINT                                  NOT NULL,
    name                        VARCHAR(255),
    short_code                  VARCHAR(255),
    description                 TEXT,
    image_url                   VARCHAR(255),
    CONSTRAINT pk_project_variants PRIMARY KEY (id)
);

CREATE TABLE projects
(
    gradable_event_id                       BIGINT  NOT NULL,
    allow_cross_course_group_project_groups BOOLEAN NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (gradable_event_id)
);

CREATE TABLE submission_requirements
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    gradable_event_id BIGINT                                  NOT NULL,
    name              VARCHAR(255),
    is_mandatory      BOOLEAN                                 NOT NULL,
    order_index       BIGINT                                  NOT NULL,
    CONSTRAINT pk_submission_requirements PRIMARY KEY (id)
);

CREATE TABLE submissions
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    submission_requirement_id BIGINT                                  NOT NULL,
    animal_id                 BIGINT                                  NOT NULL,
    url                       VARCHAR(255)                            NOT NULL,
    is_locked                 BOOLEAN                                 NOT NULL,
    created_date              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_date             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_submissions PRIMARY KEY (id)
);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_GRADABLE_EVENT FOREIGN KEY (gradable_event_id) REFERENCES gradable_events (id);

ALTER TABLE project_groups
    ADD CONSTRAINT FK_PROJECT_GROUPS_ON_INSTRUCTOR FOREIGN KEY (instructor_id) REFERENCES instructors (user_id);

ALTER TABLE project_groups
    ADD CONSTRAINT FK_PROJECT_GROUPS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (gradable_event_id);

ALTER TABLE project_variants
    ADD CONSTRAINT FK_PROJECT_VARIANTS_ON_PROJECT_VARIANT_CATEGORY FOREIGN KEY (project_variant_category_id) REFERENCES project_variant_categories (id);

ALTER TABLE project_variant_categories
    ADD CONSTRAINT FK_PROJECT_VARIANT_CATEGORIES_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (gradable_event_id);

ALTER TABLE submissions
    ADD CONSTRAINT FK_SUBMISSIONS_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animals (id);

ALTER TABLE submissions
    ADD CONSTRAINT FK_SUBMISSIONS_ON_SUBMISSION_REQUIREMENT FOREIGN KEY (submission_requirement_id) REFERENCES submission_requirements (id);

ALTER TABLE submission_requirements
    ADD CONSTRAINT FK_SUBMISSION_REQUIREMENTS_ON_GRADABLE_EVENT FOREIGN KEY (gradable_event_id) REFERENCES gradable_events (id);

ALTER TABLE project_groups_animals
    ADD CONSTRAINT fk_progroani_on_animal FOREIGN KEY (animal_id) REFERENCES animals (id);

ALTER TABLE project_groups_animals
    ADD CONSTRAINT fk_progroani_on_project_group FOREIGN KEY (project_group_id) REFERENCES project_groups (id);

ALTER TABLE project_groups_project_variants
    ADD CONSTRAINT fk_progroprovar_on_project_group FOREIGN KEY (project_group_id) REFERENCES project_groups (id);

ALTER TABLE project_groups_project_variants
    ADD CONSTRAINT fk_progroprovar_on_project_variant FOREIGN KEY (project_variant_id) REFERENCES project_variants (id);