CREATE TABLE project_groups
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    instructor_id BIGINT                                  NOT NULL,
    project_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_project_groups PRIMARY KEY (id)
);

CREATE TABLE project_groups_animals
(
    animal_id        BIGINT NOT NULL,
    project_group_id BIGINT NOT NULL
);

ALTER TABLE project_groups
    ADD CONSTRAINT FK_PROJECT_GROUPS_ON_INSTRUCTOR FOREIGN KEY (instructor_id) REFERENCES instructors (user_id);

ALTER TABLE project_groups
    ADD CONSTRAINT FK_PROJECT_GROUPS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES gradable_events (id);

ALTER TABLE project_groups_animals
    ADD CONSTRAINT fk_progroani_on_animal FOREIGN KEY (animal_id) REFERENCES animals (id);

ALTER TABLE project_groups_animals
    ADD CONSTRAINT fk_progroani_on_project_group FOREIGN KEY (project_group_id) REFERENCES project_groups (id);