BEGIN;

CREATE TABLE submission_requirements
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    gradable_event_id BIGINT                                  NOT NULL,
    name              VARCHAR(255),
    is_mandatory      BOOLEAN                                 NOT NULL,
    order_index       BIGINT                                  NOT NULL,
    CONSTRAINT pk_submission_requirements PRIMARY KEY (id)
);

CREATE TABLE submissions
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    submission_requirement_id BIGINT                                  NOT NULL,
    animal_id                 BIGINT                                  NOT NULL,
    url                       VARCHAR(255)                            NOT NULL,
    is_locked                 BOOLEAN                                 NOT NULL,
    created_date              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_date             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_submissions PRIMARY KEY (id)
);

ALTER TABLE submissions
    ADD CONSTRAINT FK_SUBMISSIONS_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animals (id);

ALTER TABLE submissions
    ADD CONSTRAINT FK_SUBMISSIONS_ON_SUBMISSION_REQUIREMENT FOREIGN KEY (submission_requirement_id) REFERENCES submission_requirements (id);

ALTER TABLE submission_requirements
    ADD CONSTRAINT FK_SUBMISSION_REQUIREMENTS_ON_GRADABLE_EVENT FOREIGN KEY (gradable_event_id) REFERENCES gradable_events (id);

COMMIT;