CREATE TABLE project_groups_project_variants
(
    project_group_id   BIGINT NOT NULL,
    project_variant_id BIGINT NOT NULL,
    PRIMARY KEY (project_variant_id, project_group_id)
);

CREATE TABLE project_variant_categories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id BIGINT                                  NOT NULL,
    name       VARCHAR(255) NOT NULL,
    CONSTRAINT pk_project_variant_categories PRIMARY KEY (id)
);

CREATE TABLE project_variants
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_variant_category_id BIGINT                                  NOT NULL,
    name                        VARCHAR(255),
    short_code                  VARCHAR(255),
    description                 TEXT,
    image_url                   VARCHAR(255),
    CONSTRAINT pk_project_variants PRIMARY KEY (id)
);

CREATE TABLE projects
(
    id BIGINT NOT NULL,
    allow_cross_course_group_project_groups BOOLEAN NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

ALTER TABLE project_variants
    ADD CONSTRAINT FK_PROJECT_VARIANTS_ON_PROJECT_VARIANT_CATEGORY FOREIGN KEY (project_variant_category_id) REFERENCES project_variant_categories (id);

ALTER TABLE project_variant_categories
    ADD CONSTRAINT FK_PROJECT_VARIANT_CATEGORIES_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE project_groups_project_variants
    ADD CONSTRAINT fk_progroprovar_on_project_group FOREIGN KEY (project_group_id) REFERENCES project_groups (id);

ALTER TABLE project_groups_project_variants
    ADD CONSTRAINT fk_progroprovar_on_project_variant FOREIGN KEY (project_variant_id) REFERENCES project_variants (id);