CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE animals
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    student_id      BIGINT,
    course_group_id BIGINT,
    CONSTRAINT pk_animals PRIMARY KEY (id)
);

CREATE TABLE assignment_sections
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_assignment_sections PRIMARY KEY (id)
);

CREATE TABLE chests
(
    reward_id BIGINT       NOT NULL,
    behavior  VARCHAR(255) NOT NULL,
    CONSTRAINT pk_chests PRIMARY KEY (reward_id)
);

CREATE TABLE chests_items
(
    chest_id BIGINT NOT NULL,
    item_id  BIGINT NOT NULL
);

CREATE TABLE coordinators
(
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_coordinators PRIMARY KEY (user_id)
);

CREATE TABLE course_groups
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    course_id     BIGINT                                  NOT NULL,
    instructor_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_course_groups PRIMARY KEY (id)
);

CREATE TABLE courses
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    info_url       VARCHAR(255),
    coordinator_id BIGINT,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

CREATE TABLE event_sections
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                            VARCHAR(255),
    is_shown_in_road_map            BOOLEAN                                 NOT NULL,
    has_gradable_events_with_topics BOOLEAN                                 NOT NULL,
    course_id                       BIGINT                                  NOT NULL,
    order_index                     BIGINT                                  NOT NULL,
    is_hidden                       BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_event_sections PRIMARY KEY (id)
);

CREATE TABLE evolution_stages
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(1000),
    min_xp      DECIMAL(4, 1)                           NOT NULL,
    order_index BIGINT                                  NOT NULL,
    grade       DECIMAL(2, 1)                           NOT NULL,
    image_url   VARCHAR(255),
    course_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_evolution_stages PRIMARY KEY (id)
);

CREATE TABLE flat_bonus_items
(
    item_id  BIGINT        NOT NULL,
    xp_bonus DECIMAL(4, 1) NOT NULL,
    behavior VARCHAR(255)  NOT NULL,
    CONSTRAINT pk_flat_bonus_items PRIMARY KEY (item_id)
);

CREATE TABLE instructors
(
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_instructors PRIMARY KEY (user_id)
);

CREATE TABLE items
(
    reward_id        BIGINT  NOT NULL,
    "limit"          INTEGER NOT NULL,
    event_section_id BIGINT,
    CONSTRAINT pk_items PRIMARY KEY (reward_id)
);

CREATE TABLE percentage_bonus_items
(
    item_id          BIGINT  NOT NULL,
    percentage_bonus INTEGER NOT NULL,
    CONSTRAINT pk_percentage_bonus_items PRIMARY KEY (item_id)
);

CREATE TABLE project_sections
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_project_sections PRIMARY KEY (id)
);

CREATE TABLE rewards
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(1000),
    image_url   VARCHAR(255),
    order_index BIGINT                                  NOT NULL,
    course_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_rewards PRIMARY KEY (id)
);

CREATE TABLE students
(
    user_id      BIGINT  NOT NULL,
    index_number INTEGER NOT NULL,
    CONSTRAINT pk_students PRIMARY KEY (user_id)
);

CREATE TABLE test_sections
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_test_sections PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255),
    password   VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE students
    ADD CONSTRAINT uc_students_indexnumber UNIQUE (index_number);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE animals
    ADD CONSTRAINT FK_ANIMALS_ON_COURSE_GROUP FOREIGN KEY (course_group_id) REFERENCES course_groups (id);

ALTER TABLE animals
    ADD CONSTRAINT FK_ANIMALS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (user_id);

ALTER TABLE assignment_sections
    ADD CONSTRAINT FK_ASSIGNMENT_SECTIONS_ON_ID FOREIGN KEY (id) REFERENCES event_sections (id);

ALTER TABLE chests
    ADD CONSTRAINT FK_CHESTS_ON_REWARD FOREIGN KEY (reward_id) REFERENCES rewards (id);

ALTER TABLE coordinators
    ADD CONSTRAINT FK_COORDINATORS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE courses
    ADD CONSTRAINT FK_COURSES_ON_COORDINATOR FOREIGN KEY (coordinator_id) REFERENCES coordinators (user_id);

ALTER TABLE course_groups
    ADD CONSTRAINT FK_COURSE_GROUPS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE course_groups
    ADD CONSTRAINT FK_COURSE_GROUPS_ON_INSTRUCTOR FOREIGN KEY (instructor_id) REFERENCES instructors (user_id);

ALTER TABLE event_sections
    ADD CONSTRAINT FK_EVENT_SECTIONS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE evolution_stages
    ADD CONSTRAINT FK_EVOLUTION_STAGES_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE flat_bonus_items
    ADD CONSTRAINT FK_FLAT_BONUS_ITEMS_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (reward_id);

ALTER TABLE instructors
    ADD CONSTRAINT FK_INSTRUCTORS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE items
    ADD CONSTRAINT FK_ITEMS_ON_EVENT_SECTION FOREIGN KEY (event_section_id) REFERENCES event_sections (id);

ALTER TABLE items
    ADD CONSTRAINT FK_ITEMS_ON_REWARD FOREIGN KEY (reward_id) REFERENCES rewards (id);

ALTER TABLE percentage_bonus_items
    ADD CONSTRAINT FK_PERCENTAGE_BONUS_ITEMS_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (reward_id);

ALTER TABLE project_sections
    ADD CONSTRAINT FK_PROJECT_SECTIONS_ON_ID FOREIGN KEY (id) REFERENCES event_sections (id);

ALTER TABLE rewards
    ADD CONSTRAINT FK_REWARDS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE test_sections
    ADD CONSTRAINT FK_TEST_SECTIONS_ON_ID FOREIGN KEY (id) REFERENCES event_sections (id);

ALTER TABLE chests_items
    ADD CONSTRAINT fk_cheite_on_chest FOREIGN KEY (chest_id) REFERENCES chests (reward_id);

ALTER TABLE chests_items
    ADD CONSTRAINT fk_cheite_on_item FOREIGN KEY (item_id) REFERENCES items (reward_id);