ALTER TABLE gradable_events_chests
    DROP CONSTRAINT fk241p4sk7g2okisg2g7urohvlk;

ALTER TABLE flat_bonus_items
    DROP CONSTRAINT fk2j3uugkdbsl1f85wdhe43vgcb;

ALTER TABLE project_grades
    DROP CONSTRAINT fk2oi66ov7ocxnrel27gmliikbe;

ALTER TABLE project_submissions
    DROP CONSTRAINT fk2pbdrm4hegm9yn9mtiwnfcoe0;

ALTER TABLE project_groups_project_variants
    DROP CONSTRAINT fk39pinoffv27yu6w4ijbncxhd;


ALTER TABLE chests
    DROP CONSTRAINT fk4e3p447qfd658cf6nav2fbbxi;

ALTER TABLE grades
    DROP CONSTRAINT fk4yf2t46gp5g4xpj0qsk60oscc;

ALTER TABLE percentage_bonus_items
    DROP CONSTRAINT fk5fgm6l356qx9ijkd76mbka3fm;

ALTER TABLE tests
    DROP CONSTRAINT fk5mpmru0qur544davm41cql79e;

ALTER TABLE tests
    DROP CONSTRAINT fk5ykt2j3uq7wyfjcg0ogyc7tcx;

ALTER TABLE assignment_submissions
    DROP CONSTRAINT fk75ad2rvqyfue5326y9p7prbwp;

ALTER TABLE project_criteria
    DROP CONSTRAINT fk7o9f520ekwtl7q8s44hsm23o2;

ALTER TABLE assignments
    DROP CONSTRAINT fk9cr2qta0h1dvnaj2nn8uo3vj9;

ALTER TABLE project_variants
    DROP CONSTRAINT fkagwjqc9k46b5n6iasusqijius;

ALTER TABLE project_groups_project_variants
    DROP CONSTRAINT fkaih0xgx0cjtb327j93skwjqbt;

ALTER TABLE project_groups_animals
    DROP CONSTRAINT fkb9eehc8msg4l63ot64nyqhfiv;

ALTER TABLE project_criteria
    DROP CONSTRAINT fkd3f9840xcwou2vu881b4uhptd;

ALTER TABLE submissions
    DROP CONSTRAINT fkdcqoxhncyqiio4yvdr7g4equi;

ALTER TABLE assigned_items
    DROP CONSTRAINT fkecui96ay4ydj1sf4geostlykg;

ALTER TABLE chests_items
    DROP CONSTRAINT fkenkbh4eptlrbeuvujea4x54tp;

ALTER TABLE project_grades
    DROP CONSTRAINT fkfxek3k7slkua515cki3hovcs3;

ALTER TABLE assigned_chests
    DROP CONSTRAINT fkgy7d0jvx8ogdecoqp3pnx9b0a;

ALTER TABLE project_submissions
    DROP CONSTRAINT fkhc7pe1kdwhh1nlkrcab17vrrr;

ALTER TABLE assignments
    DROP CONSTRAINT fkhju4t09ogfwpytli7extlta7v;

ALTER TABLE assigned_chests
    DROP CONSTRAINT fkivofkfllytc13x2vu8xjyk2i6;

ALTER TABLE project_groups_animals
    DROP CONSTRAINT fkjopxstdwt1hu76tcp1kb3cpiq;

ALTER TABLE gradable_events_chests
    DROP CONSTRAINT fkkkad7jnatbue2aev70xorufit;

ALTER TABLE chests_items
    DROP CONSTRAINT fkl1gp1pn8mv1tf106fp1rys81s;

ALTER TABLE assignment_submissions
    DROP CONSTRAINT fkm7i7ubgh7y2n6mvg8muw62oax;

ALTER TABLE test_grades
    DROP CONSTRAINT fkmlmo4ykdy6ahiy7rg3uu6r4ic;

ALTER TABLE assignment_grades
    DROP CONSTRAINT fkncvuutwcr99jyo2vtlsr83urt;

ALTER TABLE assigned_items
    DROP CONSTRAINT fkol10xaalbhs77ewydc7rv7ken;

ALTER TABLE grades
    DROP CONSTRAINT fkphk4y1cex4fhnh2jefvch2bcc;

ALTER TABLE project_variant_catogories
    DROP CONSTRAINT fkpp4y6y4we0h22p9k2sb43sss0;


ALTER TABLE assignment_grades
    DROP CONSTRAINT fkrg3a4ioyqtjqtimumh7186l0u;

CREATE TABLE animals
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    student_id      BIGINT,
    course_group_id BIGINT,
    CONSTRAINT pk_animals PRIMARY KEY (id)
);

CREATE TABLE reward
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(1000),
    image_url   VARCHAR(255),
    order_index BIGINT                                  NOT NULL,
    course_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_reward PRIMARY KEY (id)
);

INSERT INTO reward (id, name, description, image_url, order_index, course_id)
SELECT id, name, description, image_url, 0, 1
FROM items;

INSERT INTO reward (id, name, description, image_url, order_index, course_id)
SELECT id + 100, name, description, image_url, 0, course_id
FROM chests;

UPDATE chests
SET id = id + 100
WHERE id IN (SELECT id FROM chests);

UPDATE chests_items
SET chest_id = chest_id + 100;


ALTER TABLE event_sections
    ADD has_gradable_events_with_topics BOOLEAN;

ALTER TABLE event_sections
    ADD is_hidden BOOLEAN;

ALTER TABLE event_sections
    ADD is_shown_in_road_map BOOLEAN;

ALTER TABLE event_sections
    ADD order_index BIGINT;

UPDATE event_sections
SET has_gradable_events_with_topics = 'false'
WHERE has_gradable_events_with_topics IS NULL;
ALTER TABLE event_sections
    ALTER COLUMN has_gradable_events_with_topics SET NOT NULL;

UPDATE event_sections
SET is_hidden = 'false'
WHERE is_hidden IS NULL;
ALTER TABLE event_sections
    ALTER COLUMN is_hidden SET NOT NULL;

UPDATE event_sections
SET is_shown_in_road_map = 'true'
WHERE is_shown_in_road_map IS NULL;
ALTER TABLE event_sections
    ALTER COLUMN is_shown_in_road_map SET NOT NULL;

UPDATE event_sections
SET order_index = '0'
WHERE order_index IS NULL;
ALTER TABLE event_sections
    ALTER COLUMN order_index SET NOT NULL;

ALTER TABLE evolution_stages
    ADD order_index BIGINT;

UPDATE evolution_stages
SET order_index = '0'
WHERE order_index IS NULL;
ALTER TABLE evolution_stages
    ALTER COLUMN order_index SET NOT NULL;

ALTER TABLE chests
    RENAME COLUMN id to reward_id;

ALTER TABLE items
    RENAME COLUMN id TO reward_id;

ALTER TABLE animals
    ADD CONSTRAINT FK_ANIMALS_ON_COURSE_GROUP FOREIGN KEY (course_group_id) REFERENCES course_groups (id);

ALTER TABLE animals
    ADD CONSTRAINT FK_ANIMALS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (user_id);

ALTER TABLE chests
    ADD CONSTRAINT FK_CHESTS_ON_REWARD FOREIGN KEY (reward_id) REFERENCES reward (id);

ALTER TABLE flat_bonus_items
    ADD CONSTRAINT FK_FLAT_BONUS_ITEMS_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (reward_id);

ALTER TABLE items
    ADD CONSTRAINT FK_ITEMS_ON_REWARD FOREIGN KEY (reward_id) REFERENCES reward (id);

ALTER TABLE percentage_bonus_items
    ADD CONSTRAINT FK_PERCENTAGE_BONUS_ITEMS_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (reward_id);

ALTER TABLE reward
    ADD CONSTRAINT FK_REWARD_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE chests_items
    ADD CONSTRAINT fk_cheite_on_chest FOREIGN KEY (chest_id) REFERENCES chests (reward_id);

ALTER TABLE chests_items
    ADD CONSTRAINT fk_cheite_on_item FOREIGN KEY (item_id) REFERENCES items (reward_id);

DROP TABLE assigned_chests CASCADE;

DROP TABLE assigned_items CASCADE;

DROP TABLE assignment_grades CASCADE;

DROP TABLE assignment_submissions CASCADE;

DROP TABLE assignments CASCADE;

DROP TABLE coursework_sections CASCADE;

DROP TABLE gradable_events CASCADE;

DROP TABLE gradable_events_chests CASCADE;

DROP TABLE grades CASCADE;

DROP TABLE project_criteria CASCADE;

DROP TABLE project_grades CASCADE;

DROP TABLE project_groups CASCADE;

DROP TABLE project_groups_animals CASCADE;

DROP TABLE project_groups_project_variants CASCADE;

DROP TABLE project_submissions CASCADE;

DROP TABLE project_variant_catogories CASCADE;

DROP TABLE project_variants CASCADE;

INSERT INTO animals (id, name, student_id, course_group_id)
SELECT
    scg.id,
    scg.name,
    scg.student_id,
    scg.course_group_id
FROM students_course_groups scg;

DROP TABLE students_course_groups CASCADE;

DROP TABLE submissions CASCADE;

DROP TABLE test_grades CASCADE;

DROP TABLE tests CASCADE;

ALTER TABLE chests_items
    DROP CONSTRAINT chests_items_pkey;

ALTER TABLE chests
    DROP COLUMN course_id;

ALTER TABLE chests
    DROP COLUMN description;

ALTER TABLE chests
    DROP COLUMN image_url;

ALTER TABLE chests
    DROP COLUMN name;

ALTER TABLE items
    DROP COLUMN description;

ALTER TABLE items
    DROP COLUMN image_url;

ALTER TABLE items
    DROP COLUMN name;

ALTER TABLE assignment_sections
    DROP COLUMN contains_topics;

ALTER TABLE test_sections
    DROP COLUMN contains_topics;

ALTER TABLE project_sections
    DROP COLUMN hidden;

ALTER TABLE project_sections
    DROP COLUMN info_url;

ALTER TABLE project_sections
    DROP COLUMN road_map_order;

ALTER TABLE event_sections
    DROP COLUMN priority;

ALTER TABLE event_sections
    DROP COLUMN shown_in_road_map;

ALTER TABLE evolution_stages
    ALTER COLUMN description DROP NOT NULL;

ALTER TABLE users
    ALTER COLUMN email DROP NOT NULL;

ALTER TABLE users
    ALTER COLUMN first_name DROP NOT NULL;

ALTER TABLE evolution_stages
    ALTER COLUMN image_url DROP NOT NULL;

ALTER TABLE courses
    ALTER COLUMN info_url DROP NOT NULL;

ALTER TABLE users
    ALTER COLUMN last_name DROP NOT NULL;

ALTER TABLE course_groups
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE courses
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE event_sections
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE evolution_stages
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE users
    ALTER COLUMN password DROP NOT NULL;


ALTER TABLE flat_bonus_items
    DROP CONSTRAINT flat_bonus_items_behavior_check;

UPDATE flat_bonus_items
SET behavior = CASE
                   WHEN behavior = 'ONE_EVENT_TRIGGERED' THEN 'ONE_EVENT'
                   WHEN behavior = 'MULTIPLE_EVENTS_INSTANT' THEN 'MULTIPLE_EVENTS'
    END;

ALTER TABLE flat_bonus_items
    ADD CONSTRAINT flat_bonus_items_behavior_check
        CHECK (behavior IN ('ONE_EVENT', 'MULTIPLE_EVENTS'));