CREATE TABLE gradable_events
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    event_section_id     bigint                                                     NOT NULL,
    name                 varchar(64)                                                NOT NULL,
    topic                varchar(64),
    order_index          int                                                        NOT NULL,
    road_map_order_index int,
    markdown_source_url  varchar(128),
    markdown             text                                                       NOT NULL,
    is_hidden            boolean                                                    NOT NULL DEFAULT false,
    is_locked            boolean                                                    NOT NULL DEFAULT false
);

ALTER TABLE gradable_events
    ADD FOREIGN KEY (event_section_id) REFERENCES event_sections (id);

CREATE TABLE grades
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    gradable_event_id bigint                                                     NOT NULL,
    animal_id         bigint                                                     NOT NULL,
    created_date      timestamp                                                  NOT NULL,
    modified_date     timestamp                                                  NOT NULL,
    comment           text
);

ALTER TABLE grades
    ADD FOREIGN KEY (gradable_event_id) REFERENCES gradable_events (id);

ALTER TABLE grades
    ADD FOREIGN KEY (animal_id) REFERENCES animals (id);

CREATE TABLE criteria
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    gradable_event_id bigint                                                     NOT NULL,
    name              varchar(64)                                                NOT NULL,
    max_xp            int                                                        NOT NULL
);

ALTER TABLE criteria
    ADD FOREIGN KEY (gradable_event_id) REFERENCES gradable_events (id);

CREATE TABLE criteria_grades
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    grade_id     bigint                                                     NOT NULL,
    criterion_id bigint                                                     NOT NULL,
    xp           decimal(4, 1)                                              NOT NULL
);

ALTER TABLE criteria_grades
    ADD FOREIGN KEY (grade_id) REFERENCES grades (id);

ALTER TABLE criteria_grades
    ADD FOREIGN KEY (criterion_id) REFERENCES criteria (id);

CREATE TABLE criteria_rewards
(
    criterion_id bigint NOT NULL,
    reward_id    bigint NOT NULL,
    max_amount   int    NOT NULL,
    PRIMARY KEY (criterion_id, reward_id)
);

ALTER TABLE criteria_rewards
    ADD FOREIGN KEY (criterion_id) REFERENCES criteria (id);

ALTER TABLE criteria_rewards
    ADD FOREIGN KEY (reward_id) REFERENCES rewards (id);

CREATE TABLE assigned_rewards
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    criterion_grade_id bigint                                                     NOT NULL,
    reward_id          bigint                                                     NOT NULL,
    received_date      timestamp                                                  NOT NULL,
    used_date          timestamp,
    is_used            bool                                                       NOT NULL DEFAULT false
);

ALTER TABLE assigned_rewards
    ADD FOREIGN KEY (criterion_grade_id) REFERENCES criteria_grades (id);

ALTER TABLE assigned_rewards
    ADD FOREIGN KEY (reward_id) REFERENCES rewards (id);

CREATE TABLE assigned_chests
(
    assigned_reward_id BIGINT UNIQUE PRIMARY KEY NOT NULL
);

ALTER TABLE assigned_chests
    ADD FOREIGN KEY (assigned_reward_id) REFERENCES assigned_rewards (id);

CREATE TABLE assigned_items
(
    assigned_reward_id BIGINT UNIQUE PRIMARY KEY NOT NULL,
    assigned_chest_id  bigint
);

ALTER TABLE assigned_items
    ADD FOREIGN KEY (assigned_reward_id) REFERENCES assigned_rewards (id);

ALTER TABLE assigned_items
    ADD FOREIGN KEY (assigned_chest_id) REFERENCES assigned_chests (assigned_reward_id);