CREATE TABLE gradable_events
(
    id                   INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    event_section_id     int                                                     NOT NULL,
    name                 varchar(64)                                             NOT NULL,
    topic                varchar(64),
    order_index          int                                                     NOT NULL,
    road_map_order_index int,
    markdown_source_url  varchar(128),
    markdown             text                                                    NOT NULL,
    is_hidden            boolean                                                 NOT NULL DEFAULT false,
    is_locked            boolean                                                 NOT NULL DEFAULT false
);

ALTER TABLE gradable_events
    ADD FOREIGN KEY (event_section_id) REFERENCES event_sections (id);

CREATE TABLE grades
(
    id                INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    gradable_event_id int                                                     NOT NULL,
    animal_id         int                                                     NOT NULL,
    created_date      timestamp                                               NOT NULL,
    modified_date     timestamp                                               NOT NULL,
    comment           text
);

ALTER TABLE grades
    ADD FOREIGN KEY (gradable_event_id) REFERENCES gradable_events (id);

ALTER TABLE grades
    ADD FOREIGN KEY (animal_id) REFERENCES animals (id);

CREATE TABLE criteria_grades
(
    id           INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    grade_id     int                                                     NOT NULL,
    criterion_id int                                                     NOT NULL,
    xp           decimal(4, 1)                                           NOT NULL
);

ALTER TABLE criteria_grades
    ADD FOREIGN KEY (grade_id) REFERENCES grades (id);

-- ALTER TABLE criteria_grades ADD FOREIGN KEY (criterion_id) REFERENCES criteria (id);