CREATE TABLE invitation_tokens
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token        VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    expiry_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    used         BOOLEAN                                 NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_invitation_tokens PRIMARY KEY (id)
);

ALTER TABLE invitation_tokens
    ADD CONSTRAINT uc_invitation_tokens_token UNIQUE (token);

CREATE INDEX idx_invitation_tokens_email ON invitation_tokens(email);
CREATE INDEX idx_invitation_tokens_token ON invitation_tokens(token);
CREATE INDEX idx_invitation_tokens_expiry_date ON invitation_tokens(expiry_date);

ALTER TABLE users DROP COLUMN is_password_temporary;

ALTER TABLE users
ALTER COLUMN password DROP NOT NULL;