name: Build and Deploy Backend to Staging

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/polymorphia-backend/polymorphia-backend"
          docker build -t $IMAGE_NAME:staging-latest -f polymorphia-backend/Dockerfile polymorphia-backend
          docker push $IMAGE_NAME:staging-latest

      - name: Deploy on staging VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.STAGING_VM_IP }}
          username: ${{ secrets.STAGING_VM_USER }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          script: |
            IMAGE_NAME="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/polymorphia-backend/polymorphia-backend"
            
            gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
            docker pull $IMAGE_NAME:staging-latest
            docker stop polymorphia-backend || true
            docker rm polymorphia-backend || true
            docker run -d --name polymorphia-backend -p 8080:8080 \
              -v /app/config:/app/config \
              -v ~/polymorphia-static:/app/static \
              $IMAGE_NAME:staging-latest \
              --spring.config.location=file:/app/config/application.properties

