name: Deploy and Build Docker Image on Oracle Cloud VM

on:
  push:
    branches:
      - CI/CD-setup 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy files to Oracle Cloud VM
        run: |
          # Używamy scp do skopiowania plików do VM na Oracle Cloud
          scp -i ${{ secrets.OCI_PRIVATE_KEY }} -o StrictHostKeyChecking=no -r ./ ${{ secrets.OCI_USERNAME }}@${{ secrets.OCI_VM_PUBLIC_IP }}:/home/ubuntu/polymorphia-backend

      - name: Build Docker image on Oracle Cloud VM
        run: |
          ssh -i ${{ secrets.OCI_PRIVATE_KEY }} -o StrictHostKeyChecking=no ${{ secrets.OCI_USERNAME }}@${{ secrets.OCI_VM_PUBLIC_IP }} << 'EOF'
            cd /home/ubuntu/polymorphia-backend
            docker build -t polymorphia-backend .
          EOF

      - name: Run Docker container on Oracle Cloud VM
        run: |
          ssh -i ${{ secrets.OCI_PRIVATE_KEY }} -o StrictHostKeyChecking=no ${{ secrets.OCI_USERNAME }}@${{ secrets.OCI_VM_PUBLIC_IP }} << 'EOF'
            cd /home/ubuntu/polymorphia-backend
            docker run -d --name polymorphia-backend-container -p 8080:8080 polymorphia-backend
          EOF
