name: Deploy and Build Docker Image on Google Cloud

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install rsync
        run: |
          sudo apt update
          sudo apt install -y rsync openssh-client

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.OCI_VM_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Copy files 
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.OCI_USERNAME }}@${{ secrets.OCI_VM_PUBLIC_IP }}:~/polymorphia

      - name: Build and Run Docker container 
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
            ${{ secrets.OCI_USERNAME }}@${{ secrets.OCI_VM_PUBLIC_IP }} << EOF
              set -e
              cd ~/polymorphia/polymorphia-backend
              sudo systemctl start docker || true
              sudo docker stop polymorphia-backend || true
              sudo docker rm polymorphia-backend || true
              sudo docker build -t polymorphia-backend .
              sudo docker run -d -p 8080:8080 -v /app/config:/app/config -v ~/polymorphia-static:/app/static --name polymorphia-backend polymorphia-backend --spring.config.location=file:/app/config/application.properties
          EOF
