name: Build and Deploy Backend to Develop Testing

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup gcloud & Docker auth
        uses: google-github-actions/setup-gcloud@v2

      - run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build & push image
        run: |
          IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/polymorphia-backend/polymorphia-backend:develop-latest"
          docker build -t "$IMAGE" -f polymorphia-backend/Dockerfile polymorphia-backend
          docker push "$IMAGE"

    outputs:
      image: ${{ steps.build-and-push.outputs.image }}

  migrate:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH & run Flyway
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.STAGING_VM_IP }}
          username: ${{ secrets.STAGING_VM_USER }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          script: |
            if ! command -v flyway >/dev/null; then
              curl -fsSL https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.12.0/flyway-commandline-11.12.0-linux-x64.tar.gz \
              | tar -xz -C /tmp
              sudo ln -sf /tmp/flyway-11.12.0/flyway /usr/local/bin/flyway
            fi

            export FLYWAY_URL="jdbc:postgresql://${{ secrets.TEST_DB_HOST }}:${{ secrets.TEST_DB_PORT }}/${{ secrets.TEST_DB_NAME }}"
            export FLYWAY_USER="${{ secrets.TEST_DB_USER }}"
            export FLYWAY_PASSWORD="${{ secrets.TEST_DB_PASSWORD }}"

            git clone --depth 1 https://github.com/${{ github.repository }} repo

            flyway -locations=filesystem:repo/polymorphia-backend/src/main/resources/db/migration clean
            flyway -locations=filesystem:repo/polymorphia-backend/src/main/resources/db/migration migrate

  deploy:
    needs: migrate
    runs-on: ubuntu-latest
    steps:
      - name: SSH & deploy container
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.STAGING_VM_IP }}
          username: ${{ secrets.STAGING_VM_USER }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          script: |
            IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/polymorphia-backend/polymorphia-backend:develop-latest"

            gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
            docker pull "$IMAGE"

            docker stop polymorphia-backend || true
            docker rm polymorphia-backend || true

            docker run -d --name polymorphia-backend \
              -p 8080:8080 \
              -v /app/config:/app/config \
              -v ~/polymorphia-static:/app/static \
              "$IMAGE" \
              --spring.config.location=file:/app/config/application-dev.properties
