name: Build and Deploy Backend to Staging

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  setup-environment: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean old code on VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.STAGING_VM_IP }}
          username: ${{ secrets.STAGING_VM_USER }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          script: |
            rm -rf ~/polymorphia

      - name: Clone repository to VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.STAGING_VM_IP }}
          username: ${{ secrets.STAGING_VM_USER }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          script: |
            git clone --depth 1 --branch "develop" https://github.com/${{ github.repository }}.git ~/polymorphia

  build-backend:
    needs: setup-environment
    runs-on: ubuntu-latest
    
    steps:
      - name: Build Docker image
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.STAGING_VM_IP }}
          username: ${{ secrets.STAGING_VM_USER }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          script: |
            cd ~/polymorphia/polymorphia-backend
            docker build -t polymorphia-backend:staging-latest -f Dockerfile .

  run-backend: 
    needs: build-backend
    runs-on: ubuntu-latest

    steps:
      - name: Run backend on VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.STAGING_VM_IP }}
          username: ${{ secrets.STAGING_VM_USER }}
          key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          script: |
            docker stop polymorphia-backend-staging || true
            docker rm polymorphia-backend-staging || true
            docker run -d --name polymorphia-backend-staging -p 8080:8081 \
              -v /app/config:/app/config \
              -v ~/polymorphia-static:/app/static \
              polymorphia-backend:staging-latest \
              --spring.config.location=file:/app/config/application-dev.properties 

  deploy-success:
    needs: [setup-environment, build-backend, run-backend]
    runs-on: ubuntu-latest
    
    steps:
      - name: All jobs completed successfully
        run: echo "All deployment jobs completed successfully!" 

